# fly.toml app configuration file generated for yeeter-2024 on 2024-11-10T21:54:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yeeter-2024'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  FILESYSTEM_DISK = 's3'
  FLY_API_HOSTNAME='_api.internal:4280'
  FLY_APP_NAME='yeeter-2024'
  FLY_WORKER_ID='7843d19c45e538'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
    app = ""
    worker = "php artisan queue:work --stop-when-empty"

[[vm]]
  size = 'shared-cpu-2x'
  memory = 512
